<?php

namespace AppBundle\Repository;

/**
 * ReformeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReformeRepository extends \Doctrine\ORM\EntityRepository
{
}
