imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.path.acqpdf: /uploads/pdf/

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false    

vich_uploader:
    db_driver: orm
    mappings:
        pdf:
            uri_prefix:         '%app.path.acqpdf%'
            upload_destination: '%kernel.root_dir%/../web%app.path.acqpdf%'



# app/config/config.yml
easy_admin:
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
        number: '%.2f'
    site_name: 'ORMVAO <em style="font-size: 80%;">Parc Auto</em>'
    design:
        # 'dark' is the default value
        color_scheme: 'light'
    entities:
        Fournisseur:
            class: AppBundle\Entity\Fournisseur
            label: 'Fournisseur'
            list:
                actions:
                    - { name: 'show', icon: 'search', label: 'show' }
                    - { name: 'edit', icon: 'pencil', label: 'edit' }
                    - { name: 'delete', icon: 'trash', label: 'delete' }
                title: "Lister Fournisseurs"
                fields: ['id', 'Nom', 'Adresse', 'tel', { property: 'mail', type: 'email', label: 'Email' }, { property: 'activite', label: 'Activité' }]
            show:
                title: "Visualiser Fournisseurs"
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'edit' }
                    - { name: 'delete', icon: 'trash', label: 'delete' }
                fields: ['id', 'Nom', 'Adresse', 'tel', { property: 'mail', type: 'email', label: 'Email' }, { property: 'activite', label: 'Activité' }]
            search:
                title: "Chercher Fournisseurs"
                actions:
                    - { name: 'show', icon: 'search', label: 'show' }
                    - { name: 'edit', icon: 'pencil', label: 'edit' }
                    - { name: 'delete', icon: 'trash', label: 'delete' }
                fields: ['id', 'Nom', 'Adresse', 'tel', { property: 'mail', type: 'email', label: 'Email' }, { property: 'activite', label: 'Activité' }]
            edit:
                title: "Modifier Fournisseurs"
                actions:
                    - { name: 'show', icon: 'search', label: 'show' }
                    - { name: 'delete', icon: 'trash', label: 'delete' }
                fields: ['id', 'Nom', 'Adresse', 'tel', { property: 'mail', type: 'email', label: 'Email' }, { property: 'activite', label: 'Activité' }]
        Acquisition:
            class: AppBundle\Entity\Acquisition
            label: 'Acquisition'
            form:
                fields:
                    - ref
                    - dateAcq
                    - montant
                    - {property: 'voie', type: 'choice', type_options:{ choices: {'Marché': 'Marché', 'SNTL': 'SNTL' } }     }
                    - fournisseur
                    - { property: 'filename', type: 'vich_file' }
            list:
                actions:
                    - { name: 'show', icon: 'search', label: 'show' }
                    - { name: 'edit', icon: 'pencil', label: 'edit' }
                    - { name: 'delete', icon: 'trash', label: 'delete' }
        Vehicule:
            class: AppBundle\Entity\Vehicule
            label: 'Vehicule'
        Reforme:
            class: AppBundle\Entity\Reforme
            label: 'Proposition Reforme'
        Decision:
            class: AppBundle\Entity\Decision
            label: 'Decision Reforme'
            form:
                fields:
                    - numdecision
                    - datereforme
                    - datevente
                    - acquirreur
                    - prix
                    - reforme
                    - { property: 'filename', type: 'vich_file' }