app:
    resource: '@AppBundle/Controller/'
    type: annotation

# app/config/routing.yml
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin